name: ci

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  build-fcitx5-msys:
    runs-on: windows-2025
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Lint
        run: ./win32/scripts/lint.ps1

      - name: Install dependencies
        run: |
          C:/msys64/usr/bin/pacman -Syu --noconfirm
          C:/msys64/usr/bin/pacman -S --noconfirm `
            mingw-w64-clang-x86_64-extra-cmake-modules `
            cmake `
            fmt `
            gcc `
            gettext-devel `
            libuv-devel `
            msys2-runtime-devel `
            ninja
          cp -r its C:/msys64/usr/share/gettext
          Add-Content $env:GITHUB_PATH "C:/msys64/usr/bin"

      - name: Build
        run: |
          cmake -B build -G Ninja `
            -DCMAKE_BUILD_TYPE=Release
          cmake --build build

      - name: Setup tmate session
        if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v3

  build-fcitx5-clang:
    runs-on: windows-2025
    strategy:
      fail-fast: false
      matrix:
        env: [clang64, clangarm64]
        include:
          - { env: clang64, arch: AMD64, pkg_arch: x86_64, postfix: x86_64 }
          - { env: clangarm64, arch: ARM64, pkg_arch: aarch64, postfix: arm64 }

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install dependencies
        run: |
          C:/msys64/usr/bin/pacman -Syu --noconfirm
          C:/msys64/usr/bin/pacman -S --noconfirm `
            mingw-w64-clang-${{ matrix.pkg_arch }}-extra-cmake-modules `
            mingw-w64-clang-${{ matrix.pkg_arch }}-dlfcn `
            mingw-w64-clang-${{ matrix.pkg_arch }}-fmt `
            mingw-w64-clang-${{ matrix.pkg_arch }}-libuv `
            mingw-w64-clang-x86_64-clang `
            mingw-w64-clang-x86_64-cmake `
            mingw-w64-clang-x86_64-ninja `
            mingw-w64-clang-x86_64-pkgconf `
            gettext
          mkdir -p C:/msys64/usr/share/gettext
          cp -r its C:/msys64/usr/share/gettext
          Add-Content $env:GITHUB_PATH "C:/msys64/clang64/bin"
          git apply --directory=fcitx5 patches/fcitx5.patch

      - name: Build
        run: |
          cmake -B build/${{ matrix.postfix }} -G Ninja `
            -DCMAKE_BUILD_TYPE=Release `
            -DCMAKE_TOOLCHAIN_FILE='windows-cross/msys2.toolchain.cmake' `
            -DARCH=${{ matrix.arch }}
          cmake --build build/${{ matrix.postfix }}

      - name: Package
        env:
          DESTDIR: dist/${{ matrix.postfix }}
        run: |
          cmake --install build
          cd dist/${{ matrix.postfix }} && tar cjf ../Fcitx5-${{ matrix.postfix }}-dev.tar.bz2 bin/lib* lib

      - name: Setup tmate session
        if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v3

  build-win32:
    runs-on: windows-2025
    defaults:
      run:
        working-directory: win32
    steps:
      - name: Disable CRLF
        working-directory: .
        run: git config --global core.autocrlf false

      - uses: actions/checkout@v4

      - name: Build
        run: |
          cmake -B build -G Ninja `
            -DCMAKE_BUILD_TYPE=Release
          cmake --build build

      - name: Test
        run: ctest --test-dir build --output-on-failure

      - name: Check validity
        run: md5sum -c checksum

      - name: Setup tmate session
        if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v3
